/*
 * Projeto SI400A - Flor do Norte Limpeza e Organização
 * Luis Miguel Barletta Filho - RA 024446
 * 
 * 
 */
package View;

import java.awt.Component;
import projeto.flor.pkgdo.norte.Archive;
import projeto.flor.pkgdo.norte.ColecoesDeDados;

/**
 *
 * @author l024446
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmPrincipal = new javax.swing.JMenu();
        novoCadastro = new javax.swing.JMenuItem();
        jmLogin = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenuItem();
        jmCliente = new javax.swing.JMenu();
        atualizarCadastroCliente = new javax.swing.JMenuItem();
        exibirAgenda = new javax.swing.JMenuItem();
        sairCliente = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        atualizarCadastroColaborador = new javax.swing.JMenuItem();
        exibirAgendaColaborador = new javax.swing.JMenuItem();
        sairColaborador = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        sobreSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setAutoscrolls(true);

        jmPrincipal.setText("Principal");
        jmPrincipal.setPreferredSize(new java.awt.Dimension(150, 21));
        jmPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPrincipalActionPerformed(evt);
            }
        });

        novoCadastro.setText("Novo Cadastro");
        novoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoCadastroActionPerformed(evt);
            }
        });
        jmPrincipal.add(novoCadastro);

        jmLogin.setText("Login");
        jmLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmLoginActionPerformed(evt);
            }
        });
        jmPrincipal.add(jmLogin);

        sair.setText("Sair");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jmPrincipal.add(sair);

        jMenuBar1.add(jmPrincipal);

        jmCliente.setText("Cliente");
        jmCliente.setPreferredSize(new java.awt.Dimension(150, 21));

        atualizarCadastroCliente.setText("Atualizar Cadastro");
        atualizarCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarCadastroClienteActionPerformed(evt);
            }
        });
        jmCliente.add(atualizarCadastroCliente);

        exibirAgenda.setText("Agenda de Serviços");
        exibirAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirAgendaActionPerformed(evt);
            }
        });
        jmCliente.add(exibirAgenda);

        sairCliente.setText("Sair");
        sairCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairClienteActionPerformed(evt);
            }
        });
        jmCliente.add(sairCliente);

        jMenuBar1.add(jmCliente);

        jMenu1.setText("Colaborador");
        jMenu1.setPreferredSize(new java.awt.Dimension(150, 21));

        atualizarCadastroColaborador.setText("Atualizar Cadastro");
        atualizarCadastroColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarCadastroColaboradorActionPerformed(evt);
            }
        });
        jMenu1.add(atualizarCadastroColaborador);

        exibirAgendaColaborador.setText("Agenda de Serviços");
        exibirAgendaColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirAgendaColaboradorActionPerformed(evt);
            }
        });
        jMenu1.add(exibirAgendaColaborador);

        sairColaborador.setText("Sair");
        sairColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairColaboradorActionPerformed(evt);
            }
        });
        jMenu1.add(sairColaborador);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");
        jMenu2.setPreferredSize(new java.awt.Dimension(150, 21));
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        sobreSistema.setText("Sobre o sistema");
        sobreSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreSistemaActionPerformed(evt);
            }
        });
        jMenu2.add(sobreSistema);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void novoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoCadastroActionPerformed
        TelaCadastroUsuario telacadastro; 
        telacadastro = new TelaCadastroUsuario();
        Component add = jDesktopPane1.add(telacadastro);
        telacadastro.setVisible(true);
    }//GEN-LAST:event_novoCadastroActionPerformed

    private void jmPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPrincipalActionPerformed


    }//GEN-LAST:event_jmPrincipalActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
            System.exit(0); 
    }//GEN-LAST:event_sairActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        TelaCadastroUsuario telacadastro; 
        telacadastro = new TelaCadastroUsuario();
        Component add = jDesktopPane1.add(telacadastro);
        telacadastro.setVisible(true);

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void sobreSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreSistemaActionPerformed
        
        new TelaAjuda().setVisible(true);

    }//GEN-LAST:event_sobreSistemaActionPerformed

    private void atualizarCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarCadastroClienteActionPerformed
        TelaDadosCliente telaCliente; 
        telaCliente = new TelaDadosCliente();
        Component add = jDesktopPane1.add(telaCliente);
        telaCliente.setVisible(true);
    }//GEN-LAST:event_atualizarCadastroClienteActionPerformed

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        

    }//GEN-LAST:event_sairMouseClicked

    private void exibirAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirAgendaActionPerformed
        AgendaServicosCliente telaAgendaCliente; 
        telaAgendaCliente = new AgendaServicosCliente();
        Component add = jDesktopPane1.add(telaAgendaCliente);
        telaAgendaCliente.setVisible(true);
    }//GEN-LAST:event_exibirAgendaActionPerformed

    private void sairClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairClienteActionPerformed
            System.exit(0); 
    }//GEN-LAST:event_sairClienteActionPerformed

    private void atualizarCadastroColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarCadastroColaboradorActionPerformed

        TelaDadosColaborador telaColaborador; 
        telaColaborador = new TelaDadosColaborador();
        Component add = jDesktopPane1.add(telaColaborador);
        telaColaborador.setVisible(true);

    }//GEN-LAST:event_atualizarCadastroColaboradorActionPerformed

    private void exibirAgendaColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirAgendaColaboradorActionPerformed
        // TODO add your handling code here:
        AgendaServicosColaborador telaAgendaColaborador; 
        telaAgendaColaborador = new AgendaServicosColaborador();
        Component add = jDesktopPane1.add(telaAgendaColaborador);
        telaAgendaColaborador.setVisible(true);
    }//GEN-LAST:event_exibirAgendaColaboradorActionPerformed

    private void sairColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairColaboradorActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairColaboradorActionPerformed

    private void jmLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmLoginActionPerformed
        TelaLogin telaLogin; 
        telaLogin = new TelaLogin();
        Component add = jDesktopPane1.add(telaLogin);
        telaLogin.setVisible(true);
    }//GEN-LAST:event_jmLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem atualizarCadastroCliente;
    private javax.swing.JMenuItem atualizarCadastroColaborador;
    private javax.swing.JMenuItem exibirAgenda;
    private javax.swing.JMenuItem exibirAgendaColaborador;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmCliente;
    private javax.swing.JMenuItem jmLogin;
    private javax.swing.JMenu jmPrincipal;
    private javax.swing.JMenuItem novoCadastro;
    private javax.swing.JMenuItem sair;
    private javax.swing.JMenuItem sairCliente;
    private javax.swing.JMenuItem sairColaborador;
    private javax.swing.JMenuItem sobreSistema;
    // End of variables declaration//GEN-END:variables
}
